### ISSUE TITLE
It's impossible to edit .ws2 scripts.

### ISSUE THREAD

**Issue by TildaRu** [kevlu123/VN-Patching-Tools#3]
It doesn't seem to matter which game's scripts I'm trying to edit, I always get the same error.
![image](https://github.com/kevlu123/VN-Patching-Tools/assets/107315419/5d1bda87-f105-48a1-91af-1d982222ea49)

**Comment by kevlu123** [comment]
I wonder if it's a problem with special characters in file paths or permission issues.

I'll do a few checks myself. I haven't tested in a Japanese locale environment before.

**Comment by kevlu123** [comment]
You currently cannot edit the names.txt or choices.txt. You can edit opcodes.json instead to change names and choices but editing each ws2 file separately will be a pain. It is therefore recommended to automate this with custom code.

There is also a newer version available (1.3.0) if you've encountered any other problems.

**Comment by kevlu123** [comment]
I've created a new version to let you edit the names.txt. Let me know if you still have any problems.

**Comment by TildaRu** [comment]
Good.
![image](https://github.com/kevlu123/VN-Patching-Tools/assets/107315419/b1051158-1b74-4ab2-a8e0-1f8fbc563b75)
