### ISSUE TITLE
hscene replay menu is missing 

### ISSUE THREAD

**Issue by the-math-god** [kevlu123/VN-Patching-Tools#5]
hi I'm super glad you managed to apply most of the fixes but i noticed 
that there's no replay hscene in the the menus 
for flight dairy

**Comment by kevlu123** [comment]
It was a lot of work to restore the CG gallery so I was kinda exhausted and didn't want to patch the replay menu if there wasn't any demand. Since you brought it up, I'll start working on it soon.

**Comment by the-math-god** [comment]
AWESOME!!!  TYA
and you enjoy the holidays before you get started on this 
since the hscenes aren't translated yet no rush

**Comment by kevlu123** [comment]
Uploading the new changes now. Merry Christmas!
